apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: system:openshift:openshift-controller-manager:update-buildconfig-status
roleRef:
  kind: ClusterRole
  name: system:openshift:openshift-controller-manager:update-buildconfig-status
subjects:
- kind: ServiceAccount
  namespace: openshift-controller-manager
  name: openshift-controller-manager-sa
- kind: ServiceAccount
  namespace: openshift-infra
  name: build-config-change-controller